CREATE DATABASE Empresa
GO

USE Empresa

CREATE TABLE Nivel(
	Id INT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Usuario(
	Id INT PRIMARY KEY IDENTITY,
	Nombre VARCHAR(15) NOT NULL,
	Contraseña VARCHAR(15) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	IdNivel INT FOREIGN KEY REFERENCES Nivel(Id)
)
GO

CREATE TABLE TipoEmpleado(
	Id INT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Empleado(
	Legajo INT PRIMARY KEY IDENTITY,
	FechaIngreso ROWVERSION,
	IdPersona INT FOREIGN KEY REFERENCES Persona(Id),
	IdTipoEmpleado INT FOREIGN KEY REFERENCES TipoEmpleado(Id)
)
GO

CREATE TABLE Sexo(
	Id INT PRIMARY KEY IDENTITY,
	Sexo VARCHAR(30) NOT NULL
)
GO

CREATE TABLE EstadoCivil(
	Id INT PRIMARY KEY IDENTITY,
	Estado VARCHAR(30) NOT NULL
)
GO

CREATE TABLE TipoVivienda(
	Id INT PRIMARY KEY IDENTITY,
	Vivienda VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Domicilio(
	Id INT PRIMARY KEY IDENTITY,
	IdTipoVivienda INT FOREIGN KEY REFERENCES TipoVivienda(Id),
	Calle VARCHAR(30) NOT NULL,
	Numero INT NOT NULL,
	Piso INT,
	Departamento VARCHAR(1)
)
GO

CREATE TABLE Persona(
	Id INT PRIMARY KEY IDENTITY,
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Dni INT NOT NULL,
	Edad INT,
	IdSexo INT FOREIGN KEY REFERENCES Sexo(Id),
	IdEstadoCivil INT FOREIGN KEY REFERENCES EstadoCivil(Id),
)
GO

CREATE TABLE MultiDomicilio(
	Id INT PRIMARY KEY IDENTITY,
	IdPersona INT FOREIGN KEY REFERENCES Persona(Id),
	IdDomicilio INT FOREIGN KEY REFERENCES Domicilio(Id),
)
GO

CREATE TABLE Junior(
	Id INT PRIMARY KEY IDENTITY,
	Lenguaje VARCHAR(20) NOT NULL,
	LegajoEmpleado INT FOREIGN KEY REFERENCES Empleado(Legajo),
)
GO

CREATE TABLE Gerente(
	Id INT PRIMARY KEY IDENTITY,
	Rango VARCHAR(20) NOT NULL,
	LegajoEmpleado INT FOREIGN KEY REFERENCES Empleado(Legajo),
)
GO