CREATE DATABASE Empresa

CREATE TABLE Nivel(
Id int PRIMARY KEY IDENTITY,
Tipo VARCHAR(20) NOT NULL
)


CREATE TABLE Usuario(
Id int PRIMARY KEY IDENTITY,
Nombre VARCHAR(15) NOT NULL,
Contraseña VARCHAR(15) NOT NULL,
Email VARCHAR(30) NOT NULL,
IdNivel int FOREIGN KEY REFERENCES Nivel(Id)
)


CREATE TABLE Empleado(
Legajo int PRIMARY KEY IDENTITY,

)